require("dotenv").config();
const path = require("path");
const express = require("express");
const app = express();
const session = require("express-session");
const cookieParser = require("cookie-parser");
const bodyParser = require("body-parser");
const flash = require("express-flash-messages");
const { applicationSecretKey } = require("../../App/Infrastructure/config");
const dataBaseConnection = require("../../App/Infrastructure/models/dataBaseConnection");
const apiRoutes = require("../routes/api/v1/apiRoutes");
const applicationRoutes = require("../routes/applicationRoutes");
app.set("views", path.join(__dirname, "../views"));
app.set("view engine", "jade");
app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(session({ secret: applicationSecretKey }));
app.use(flash());
app.use("/api/v1/", apiRoutes);
app.use(applicationRoutes);
dataBaseConnection();
module.exports = app;
